version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/.acme.sh/powerfulyang.com/:/usr/share/nginx/cert/powerfulyang.com/
      - ./www/:/usr/share/nginx/www/
      - ./nginx/404.html:/usr/share/nginx/www/404.html
      - ./nginx/conf/:/usr/share/nginx/conf/
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 4856:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      TZ: Asia/Shanghai
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --max_allowed_packet=128M --performance_schema=OFF;
    volumes:
      - ./mysql/data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: always
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --save "" --appendfsync no
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  api.powerfulyang.com:
    image: powerfulyang/api.powerfulyang.com
    container_name: api.powerfulyang.com
    volumes:
      - ./api.powerfulyang.com/assets:/usr/app/assets
      - ./api.powerfulyang.com/.cookies:/usr/app/.cookies
    restart: always
    command: npm run start:prod
    env_file:
      - ./api.powerfulyang.com/.env
    deploy:
      mode: replicated
      replicas: 4
  powerfulyang.com:
    image: powerfulyang/powerfulyang.com
    container_name: powerfulyang.com
    restart: always
    command: npm run start
    env_file:
      - ./powerfulyang.com/.env
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

